### ISSUE TITLE
Feature: User can create purchase.

### ISSUE THREAD

**Issue by Matthew-Abebe** [Matthew-Abebe/Budget-Pal#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a purchase.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will enter necessary information for a purchase and add it to the database.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot (653)](https://user-images.githubusercontent.com/44979851/119420066-72218f00-bcb0-11eb-8b6c-daf9b1e3cabf.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Define a purchase table in `schema.sql`.
- [x] Insert category data into  `data.sql`.
- [x] Confirm that purchases are being added to the database.

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] Get purchase data.
- [x] Post purchase data.
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for inputs and form submission.
- [x] Style inputs and buttons. 
- [x] Update component to listen to inputs for purchase data.

### Clean
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
