### ISSUE TITLE
Feature: User can view a chart for spending by category.

### ISSUE THREAD

**Issue by Matthew-Abebe** [Matthew-Abebe/Budget-Pal#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can view a chart for spending by category.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Select analysis tab and view charts including a chart for spending by category.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screenshot (785)](https://user-images.githubusercontent.com/44979851/120690988-bf44f400-c45a-11eb-98a8-f828c4143e86.png)
![Screenshot (786)](https://user-images.githubusercontent.com/44979851/120691002-c23fe480-c45a-11eb-8557-51fc49c8982a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] Test `purchases` with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update analysis component to have categories in state
- [x] Update analysis component to show spending by category chart

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
