### ISSUE TITLE
Feature: User can view a list of categories

### ISSUE THREAD

**Issue by Matthew-Abebe** [Matthew-Abebe/Budget-Pal#15]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can view a list of budget categories.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Select categories tab and see a list of budget categories.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screenshot (804)](https://user-images.githubusercontent.com/44979851/120720352-c4b53500-c480-11eb-9a19-99fd7ca00560.png)
![Screenshot (805)](https://user-images.githubusercontent.com/44979851/120720355-c848bc00-c480-11eb-91fd-568fb0dcc9b3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Test 'categories' with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to display a list of budget categories
- [x] Update component to take user to category form to add new category.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
