### ISSUE TITLE
Feature: User can create a note.

### ISSUE THREAD

**Issue by Matthew-Abebe** [Matthew-Abebe/Budget-Pal#17]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can create a note.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Select the notes tab and create a note.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screenshot (811)](https://user-images.githubusercontent.com/44979851/120724523-de5a7a80-c488-11eb-9434-53f0902b30dc.png)
![Screenshot (812)](https://user-images.githubusercontent.com/44979851/120724532-e31f2e80-c488-11eb-87af-72df295a6777.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database
- [x] Update `schema.sql` to create a 'notes' table

### ☁️ Server
- [x] Update `server/index.js` to ...
- [x] POST new note to 'notes' table.
- [x] Test Post notes with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client
- [x] Create a component to render a form for creating notes.
- [x] Update component to send new note to notes table in database.

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
