### ISSUE TITLE
Feature: User can view a list of notes.

### ISSUE THREAD

**Issue by Matthew-Abebe** [Matthew-Abebe/Budget-Pal#19]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can view a list of notes.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Select the notes tab and view a list of notes.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screenshot (818)](https://user-images.githubusercontent.com/44979851/120727297-0220bf00-c48f-11eb-88e8-6aa093c4a3b2.png)
![Screenshot (819)](https://user-images.githubusercontent.com/44979851/120727305-064cdc80-c48f-11eb-97fa-4b50794b2951.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server
- [x] Update `server/index.js` to GET notes from the database.
- [x] Test GET notes with HTTPie.
- [x] Handle all errors and respond to the client.

### ⚡ Client
- [x] Create a component to display a list of notes.
- [x] Update component to send user to new notes form when add new note button is clicked.

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
