### ISSUE TITLE
Feature: User can view a list of purchases.

### ISSUE THREAD

**Issue by Matthew-Abebe** [Matthew-Abebe/Budget-Pal#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can view a list of purchases.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Click the purchases link in the navbar to see a list of purchases items.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screenshot (678)](https://user-images.githubusercontent.com/44979851/119590851-64d8d300-bd8a-11eb-8290-a5cd56ad1d06.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] Test GET purchases with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a navbar component.
- [x] Update navbar component to link to purchase list.
- [x] Render purchase list items.
- [x] Add a button to purchase list that takes user to add new purchase form.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
