### ISSUE TITLE
Feature: User can edit a category.

### ISSUE THREAD

**Issue by Matthew-Abebe** [Matthew-Abebe/Budget-Pal#27]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit a category.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Select categories and choose a category to edit. User will be taken to an edit form and input new information to submit an edited card.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot (839)](https://user-images.githubusercontent.com/44979851/120872259-ff879d80-c552-11eb-813d-1e717ea691b4.png)
![Screenshot (840)](https://user-images.githubusercontent.com/44979851/120872262-044c5180-c553-11eb-97fd-303de1540188.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to have a PUT method.
- [x] Test PUT on categories with HTTPie.

### ⚡ Client

- [x] Create an edit category form component.
- [x] Update component to update a category card.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
