### ISSUE TITLE
Feature: User can create custom budget categories.

### ISSUE THREAD

**Issue by Matthew-Abebe** [Matthew-Abebe/Budget-Pal#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can create custom budget categories

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Select budget tab and create category by entering a name and an amount for category submission.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot (764)](https://user-images.githubusercontent.com/44979851/120527324-11b8de80-c38f-11eb-8b68-7911c39afd41.png)
![Screenshot (765)](https://user-images.githubusercontent.com/44979851/120527344-15e4fc00-c38f-11eb-9193-ae2a179610c1.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Add categories table to database.
- [x] Give categories table an id column, name column, and an amount column.

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] Test category data with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to make custom budget categories
- [x] Update component to add categories to categories table.
- [x] Style component.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
